### ISSUE TITLE
can't edit rows if the data key contains spaces

### ISSUE THREAD

**Issue by moham96** [KasperOlesen/DataTable-AltEditor#163]
for example in the [02_in_memory_objects example](https://github.com/KasperOlesen/DataTable-AltEditor/blob/master/example/02_in_memory_objects/example2.js) if I change `startDate` to `"start Date"` then the table loads fine but if I click on the edit button I don't see the old value of the field.

Regards

**Comment by luca-vercelli** [comment]
The reason of this bug is that we use keys as DOM id's: `id="startDate"` and we retrieve them as `$('#startDate')`. This does not work with spaces: `$('#start date')`.
A possible solution (from [StackOverflow](https://stackoverflow.com/questions/596314)) is replacing selectors with something like `$('[id='start date'])`.
However this has to be done in many many points in the code. I'm afraid this cannot be fixed.
