### ISSUE TITLE
Help Requested unknown parameter 'id' for row 0, column 0

### ISSUE THREAD

**Issue by inihaekal** [KasperOlesen/DataTable-AltEditor#90]
Hi AltEditor,

Thank you for your awesome alternate :).

I facing a problem when i try to **ADD** and **EDIT**. I receive message like this
_

> DataTables warning: table id=host - Requested unknown parameter 'id' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4

_

heres my script table : https://plnkr.co/edit/32WyF23xXWQ0gFFD?preview

thanks

**Comment by luca-vercelli** [comment]
Hello.
The problem is in the webservice answer.
AltEditor expects that the webservice returns the exact data inserted on database, and shows it in the Datatable. Your webservice
https://bundadaycare.com/itg/api/datahost.json
is returning something different (maybe the whole list?)

If you search in the closed issue, you will find that several people had a similar problem in the past. 

You can also look at the "examples" section to see what kind of answer is expected.

**Comment by inihaekal** [comment]
> Hello.
> The problem is in the webservice answer.
> AltEditor expects that the webservice returns the exact data inserted on database, and shows it in the Datatable. Your webservice
> https://bundadaycare.com/itg/api/datahost.json
> is returning something different (maybe the whole list?)
> 
> If you search in the closed issue, you will find that several people had a similar problem in the past.
> 
> You can also look at the "examples" section to see what kind of answer is expected.

Awesome !! after I test on rest API. it works properly.

but I facing another problem when I try to post or put multiple select. i get response 500.
![image](https://user-images.githubusercontent.com/62714156/79467903-819fc480-8028-11ea-9b25-625fe4740074.png)

and this one my controller
![image](https://user-images.githubusercontent.com/62714156/79468210-d6dbd600-8028-11ea-80f9-ca6746897e6b.png)

Thanks !

**Comment by luca-vercelli** [comment]
@inihaekal did you solve this?
